payments:
  service:
    url: http://localhost:8081

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 30
        failureRateThreshold: 40
        slidingWindowType: COUNT_BASED
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 50s
    instances:
      delivery:
        baseConfig: default
        minimumNumberOfCalls: 10
      payment:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 10
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 4
        waitDurationInOpenState: 20s
        failureRateThreshold: 70
        ignoreExceptions:
          - java.lang.IllegalArgumentException

resilience4j.retry:
  instances:
    payment:
      maxAttempts: 3
      waitDuration: 10s
#      retryExceptions:
#        - org.springframework.web.client.HttpServerErrorException
#        - java.io.IOException
      ignoreExceptions:
        - java.lang.IllegalArgumentException

resilience4j.ratelimiter:
  instances:
    payment:
      limitForPeriod: 2
      limitRefreshPeriod: 10s
      timeoutDuration: 2
      registerHealthIndicator: true

resilience4j.timelimiter:
  instances:
    payment:
      timeoutDuration: 2s
      cancelRunningFuture: true

resilience4j.bulkhead:
  instances:
    payment:
      maxWaitDuration: 10ms
      maxConcurrentCalls: 3

resilience4j.thread-pool-bulkhead:
  instances:
    payment:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1
      writableStackTraceEnabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

